Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    wget https://download.virtualbox.org/virtualbox/7.0.32/VBoxGuestAdditions_7.0.32.iso -P /tmp
    sudo mkdir -p /mnt/cdrom
    sudo mount -o loop /tmp/VBoxGuestAdditions_7.0.32.iso /mnt/cdrom
    sudo sh /mnt/cdrom/VBoxLinuxAdditions.run
    sudo umount /mnt/cdrom
    rm /tmp/VBoxGuestAdditions_7.0.32.iso
  SHELL
end
